# Generated by Django 6.0.1 on 2026-01-23 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('preacher_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitUsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('NW', 'NEW'), ('VS', 'VISITED'), ('CD', 'CONFIRMED'), ('CT', 'CONTACTED'), ('DN', 'DID NOT SHOW'), ('FP', 'FOLLOWED UP')], max_length=2)),
                ('intent_type', models.CharField(choices=[('VS', 'VISIT'), ('JN', 'JOIN'), ('IN', 'INFO')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timeframe', models.CharField(choices=[('CS', 'COMING SERVICE'), ('TW', 'WITHIN THE NEXT 2 WEEKS'), ('NS', 'NOT SURE'), ('IN', 'JUST INFO')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tags', models.CharField(choices=[('AS', 'Academic Seminar'), ('FS', "Fresher's Orientation"), ('RT', 'Relationship Talk'), ('FL', 'Financial Literacy'), ('CS', 'Communion Service'), ('OT', 'Other')], max_length=2)),
                ('scripture_references', models.TextField()),
                ('body', models.TextField()),
                ('date_preached', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('preacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.preacher')),
            ],
        ),
        migrations.CreateModel(
            name='VisitationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('NW', 'NEW'), ('VS', 'VISITED'), ('CD', 'CONFIRMED'), ('CT', 'CONTACTED'), ('DN', 'DID NOT SHOW'), ('FP', 'FOLLOWED UP')], max_length=2)),
                ('new_status', models.CharField(choices=[('NW', 'NEW'), ('VS', 'VISITED'), ('CD', 'CONFIRMED'), ('CT', 'CONTACTED'), ('DN', 'DID NOT SHOW'), ('FP', 'FOLLOWED UP')], max_length=2)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('visit_us_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='api.visitusinfo')),
            ],
        ),
    ]
