# Generated by Django 6.0.1 on 2026-01-28 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('first_timers_count', models.PositiveIntegerField()),
                ('total_attendance', models.PositiveIntegerField()),
                ('first_offering', models.DecimalField(decimal_places=2, max_digits=10)),
                ('second_offering', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sunday Records',
            },
        ),
        migrations.RemoveField(
            model_name='sermon',
            name='scripture_references',
        ),
        migrations.AddField(
            model_name='sermon',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ScriptureReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scripture', models.CharField(max_length=150)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sermon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripture_references', to='api.sermon')),
            ],
        ),
    ]
